FORMAT: 1A
HOST: http://localhost:8080/

# gorestapplication

This REST application to support retrive BTCUSD data from our system

## Get latest Price Collection [/getprice/last?type=BTC]

### Get last price [GET]

+ Response 200 (application/json)

        { 
            "RATE": 0.00,
            "CreatedAt": "2006-01-02 15:04:05",
            "Message": "SUCCESS/system error"
        }

## Get price by timestamp Collection [/getprice/bytimestamp?timestamp=1666964013]

### Get the price at a given timestamp [GET]

get the price at a given timestamp, come up with a way to serve a price if you don't have price at the requested second


+ Response 200 (application/json)

        { 
            "RATE": 123.32123,
            "CreatedAt": "2006-01-02 15:04:05",
            "Message": "SUCCESS/system error",
            "NearestRate" : 0.00
        }
        
        
## Get price by timestamp Collection [/getprice/average?starttime=1666964013&endtime=1666964133]

### Get Average [GET]

compute the average price in a time range

+ Response 200 (application/json)

        {
            "RATE": 0.00,
            "Message": "SUCCESS/system error"
        }