version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: "go-simple-rest-application-db"
    networks:
      - default
    restart: always
    ports:
    - "3036:3336"
    environment:
      MYSQL_DATABASE: "cryptoprice"
      MYSQL_ROOT_PASSWORD: "mysqltoor"
      MYSQL_PASSWORD: "mysqltoor"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migration:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name: "go-simple-rest-application-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
      - db
    volumes:
    - .:/app/
networks:
  default:
volumes:
  mysql_data:
